url: https://andrej.jovanovic.co.za
baseurl: ""
lang: en

# Site Settings
title: Andrej Jovanović
author: Andrej Jovanović
description: "Machine learning researcher interested in distributed and efficient machine learning at the University of Cambridge and Flower Labs."
keywords: "Distributed Machine Learning, Efficient Machine Learning, Compression, Distributed Training, Federated Learning, Deep Learning, Machine Learning, Artificial Intelligence, Self-Improving AI Systems, AI, ML"
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/detailed_front.jpeg
  - scope:
      path: ""
      type: "notes"
    values:
      seo_type: Article
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
