url: http://maddox-j.github.io
baseurl: ""

# Site Settings
title: Andrej Jovanović
description: "A budding machine learning researcher."
keywords: "Machine Learning, NLP, Research, Efficiency, Deployment"
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
