url: https://andrej.jovanovic.co.za
baseurl: ""

# Site Settings
title: Andrej Jovanović
author: Andrej Jovanović
description: "A budding machine learning researcher who is passionate about efficient and secure solutions."
keywords: "Distributed Machine Learning, Efficient Machine Learning, NLP, "
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
